project:
  type: website
  output-dir: docs

website:
  title: "Juliane Kloidt"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - cv.qmd
      - icon: envelope-at-fill 
        href: j.kloidt.1@research.gla.ac.uk 
      - icon: linkedin 
        href: https://www.linkedin.com/in/julianekloidt/
      - icon: github
        href: https://github.com/JulianeKloidt
  page-footer: 
    center: "CC-BY-SA-4.0 (2025) Juliane Kloidt"

format:
  html:
    theme: 
      light: cosmo
    css: styles.css
    toc: true

editor: visual

