---
title: "CV"
---

My full CV can be downloaded [here](Kloidt_CV.pdf).

## Professional Experience

**Independent Contractor** \| Princeton University

-   May 2025 - present \| Behavioral Science for Policy Lab

**Research Assistant** \| University of Kaiserslautern-Landau (RPTU)

-   Aug 2021 - present \| Department of Business and Economics

**Applied Researcher** \| Glasgow University

-   Aug 2021 - Nov 2025 \| College of Medical, Veterinary, and Life Sciences

**Graduate Teaching Assistant** \| University of Glasgow

-   Jan 2023 - Jul 2025 \| School of Psychology and Neuroscience

**Research Assistant** \| University of Glasgow

-   Feb 2024 - Dec 2024 \| School of Psychology and Neuroscience

## Education

**PhD with Integrated Masters** \| Computer Science and Psychology

-   Aug 2021 – Oct 2025 \| UKRI Centre for Doctoral Training in Socially Intelligent Artificial Agents

-   Scholarships: UK Research and Innovation (~£100K) with a 9.6% acceptance rate

**BSc distinguished 1st** \| Psychology with Neuroscience Specialism

-   Sep 2017 - Jun 2021 \| University of Glasgow

-   Scholarships: German Academic Scholarship Foundation (~£18K)

## Publications

**Kloidt, J.**, & Barsalou, L. (2024). *Establishing the Comprehensive Hierarchical construct of Eustress (CHE)*. Current Psychology, 1-16. <https://doi.org/10.1007/s12144-024-06750-7>

**Kloidt, J.**, & Barsalou, L. (2025). *Developing and evaluating the Comprehensive Hierarchical Eustress Review (CHER)*. PsyArXiv. <https://doi.org/10.31234/osf.io/3wmhs_v1>

**Kloidt, J.**, & Barsalou, L. (2025). *Coping, fulfilment, and successful outcomes: Assessing sources of eustress across real-life challenging situations.* PsyArXiv. <https://doi.org/10.31234/osf.io/m8txb_v1>

**Kloidt, J.**, Balaya, M., & Barsalou, L. (2025). *Establishing feature profiles of threatening and challenging situations generated with AI.* PsyArXiv. <https://doi.org/10.31234/osf.io/g4m7u_v1>

Kaiser, T., **Kloidt, J.**, Mata, J., & Hertwig, R. (2025). *A Meta-Meta-Analysis of Behavior Change Interventions: Two Tales of Behavior Change* (No. 11863). CESifo Working Paper.

Werner, J., **Kloidt, J.**, & Barsalou, L. (2022). *Assessing individual motivation for consuming diverse food groups over a two-week period*. PsyArXiv. <https://osf.io/preprints/psyarxiv/4d9xq>

## Grants & Awards

#### 2024

-   Impact Acceleration Account, Medical Research Council (£25,000)

## Selected Presentations

#### 2025

-   European Health Psychology Society, Annual Scientific Meeting (Oral Presentation)

-   UK Society for Behavioural Medicine, Annual Scientific Meeting (Oral Presentation)

-   UCL Centre for Behaviour Change, Behaviour Change for Health and Sustainability Conference (Poster)

#### 2024

-   Max Planck Institute for Human Development, Centre for Adaptive Rationality (Invited Talk)

-   University of Edinburgh, Symposium on Bridging AI and Psychology (Poster)

-   University of Glasgow, Centre for Cognition, Language, and Metascience (Invited Seminar)

#### 2023

-   ARC Pre-Accelerator, Generating Sustainable Impact at Scale (Online Pitch)

-   Social AI CDT, Annual Presentations (Poster)

#### 2022

-   University of Glasgow, Methods & Metascience Network (2x Invited Seminar)
